# +--------------------------------------------------------------------------+ #
# <                     PvPManager Configuration File                        > #
# <--------------------------------------------------------------------------> #
# <         For a more detailed explanation of each setting go to            > #
# <   http://dev.bukkit.org/bukkit-plugins/pvpmanager/pages/configuration/   > #
# +--------------------------------------------------------------------------+ #

# Informs PvPManager if the config is updated, do not touch it unless you want to reset the config
Config Version: 20
# This changes the plugin's messages to the specified language.
# Currently there is - en ru ch es
Locale: en

# Should blood animation on PvP be enabled
PvP Blood: true

# Should soup instantly heal you
Auto Soup:
  Enabled: false
  Health Gain: 6

# What should be disabled on PvP
# Disabling disguises support DisguiseCraft and LibsDisguises
# Ignore Zones For Tagged - Players can be attacked in safe zones if in combat(They can't run away from fight)
# Ignore No Damage Hits - Plugin will ignore hits from snowballs, eggs and fishing rod
Disable Fly: true
Disable GameMode: true
Disable Disguise: true
Disable Invisibility: false
Ignore Zones For Tagged: true
Ignore No Damage Hits: false

# This section defines everything that will happen when a player is tagged in combat
# Silent - Should messages be sent when players are in/out combat
# Time(seconds) - For how many seconds should the player be tagged
# Name Tag Color - Choose the color above the player when in combat, write 'none' to disable, you can also 
# write a prefix but make sure it's under 16 characters. Example - '&c[Tagged] '
# Stop Commands - Should commands be blocked in combat(Example - To prevent teleports)
# -> Allowed Commands - All commands will be blocked except the ones here
# Punishments - When player logs out in combat (PvP log), should he be punished?
# -> Broadcast PvPLog - Broadcast to all the players when someone PvP logs
# -> Log To File - Log all pvp loggers to a file
# -> Fine - Take money from player when he PvP logs (needs Vault)
In Combat:
  Enabled: true
  Silent: false
  Time(seconds): 10
  Name Tag Color: '&c'
  Only Tag Attacker: false
  Block EnderPearl: true
  Stop Commands:
    Enabled: true
    Allowed Commands:
      - tell
      - money
  Punishments:
    Enabled: true
    Broadcast PvPLog: true
    Log To File: true
    Kill on Logout: true
    Drops:
      Inventory: true
      Experience: true
      Armor: true
    Fine:
      Enabled: false
      Amount: 10.0

# Section with settings triggered when a player kills another player
# Transfer Drops - Transfer drops directly to killer instead of dropping on the ground
# Money Reward - Amount of money player gets as reward (0 to disable)
# Commands On Kill - Commands to execute on kill (<player> is the killer)
Player Kills:
  Transfer Drops: false
  Money Reward: 0
  Commands On Kill:
    Enabled: false
    Commands:
      - heal <player>

# Section for PvP Toggle command(/pvp)
# Broadcast - Broadcast a message when players toggle PvP
# Cooldown(seconds) - How many seconds players have to wait until they can use /pvp again
# Toggle Off on Death - Toggle automatically PvP off for a player on death(if player has toggle permission)
# NameTags - Control if the nametag of the player should have colors when pvp if on/off
PvP Toggle:
  Broadcast: false
  Cooldown(seconds): 15
  Toggle Off on Death: false
  NameTags:
    Enabled: false
    Color On: '&1'
    Color Off: '&2'

# Should toggle PvP signs be enabled? (Similar to /pvp command but by clicking signs)
# To create a toggle sign write [pvpmanager] on the first line (remember you need the right permission)
# Disable Toggle Command - Should /pvp command be disabled in order to force using of signs by players?
Toggle Signs:
  Enabled: true
  Disable Toggle Command: false

# This feature prevents player abuse by killing the same player several times to rise in rank or get rewards
# Example - If a player X kills player Y more than 5 times, it executes the commands defined(kick, jail, etc)
# In this case, it would check every 60 seconds for abusers
# Respawn Protection - After respawn, how many seconds should players be protected (0 to disable)
Kill Abuse:
  Enabled: true
  Max Kills: 5
  Time Limit: 60
  Commands on Abuse:
    - kick <player> Kill Abuse Is Not Allowed!
  Respawn Protection: 5

# Should new players on your server be protected from PvP (If they want to PvP just use /pvp disable protection)
# Time(minutes) - If so, for how many minutes should protection last
Newbie Protection:
  Enabled: true
  Time(minutes): 5

# Default PvP - All players should start with PvP ON(=true) or OFF(=false) by default(Only works for new players)
Default PvP: true

# Should PvPManager be allowed to check for updates and tell you about them
# Auto Update - After checking should we download it automatically for you?
Update Check:
  Enabled: true
  Auto Update: true

# In these worlds PvPManager will not have any effect
World Exclusions:
  - Example
  - Example2
